### Logout
GET http://localhost:5010/api/v1/auth/logout

### Create notes with json body
POST http://localhost:5010/api/v1/notes/create
Content-Type: application/json

{
  "title": "string",
  "description": "string",
  "content": "string",
  "userUuid": "e7a708e7-cc7c-11ee-b3a0-0242ac160002"
}

### Get Post
GET http://localhost:5010/api/v1/notes/list

### Find Content by Id
@id = 2
GET http://localhost:5010/api/v1/notes/get/{{id}}/content
