version: '3.8'
name: notes-infra
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=notes_db
      - MYSQL_ROOT_PASSWORD=123456789*
    ports:
      - '3306:3306'
    volumes:
      - ./script/database.sql:/docker-entrypoint-initdb.d/database.sql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=123456789*
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    depends_on:
      - mysql

volumes:
  test_vol:
    driver: local